[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_12"] }
draken ={ path = "../draken" }
model= { path = "../../lib/model" }
view = { path = "../../lib/view" }
controller= { path = "../../lib/controller" }
