[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../../lib/api" }
draken = { path = "../draken" }
model = { path = "../../lib/model" }
view = { path = "../../lib/view" }
controller = { path = "../../lib/controller" }
