
[workspace]
resolver = '2'
members = [
	'bin/gui',
	'bin/draken',
	'lib/view',
	'lib/controller',
	'lib/model',
	'lib/api',
	'lib/engine',
	'lib/uci',
	'lib/fen',
	'lib/pieces',
	'lib/bitboard',
	'lib/board',
	'lib/moves',
	'lib/game',
]

[profile.release]
lto = true
