
[workspace]
resolver = '2'
members = [
    'apps/gui',
    'libs/draken',
    'libs/view',
    'libs/controller',
    'libs/model',
    'libs/api',
    'libs/engine',
    'libs/uci',
    'libs/bitboard',
    'libs/board',
    'libs/game',
]

[profile.release]
lto = true
