[toolchain]
channel = "nightly-2024-02-05"
targets = [
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "i686-linux-android",
    "x86_64-linux-android",
]
components = ["llvm-tools","clippy","rustfmt"]
