[package]
name = "draken"
version = "0.0.1"
edition = "2021"
authors = ["Clemens Horn <me@clemenshorn.com>"]
about = "Plays chess"

[dependencies]

clap = { version = "4.4.18", features = ["derive"] }
