[package]
name = "draken"
version = "0.0.1"
edition = "2021"
authors = ["Clemens Horn <me@clemenshorn.com>"]
description = "Plays chess"
readme = "bin/draken/README.md"
repository = "https://github.com/clemenscodes/draken/"

[dependencies]

clap = { version = "4.4.18", features = ["derive"] }
