[package]
name = "draken"
version = "0.0.1"
edition = "2021"
description = "Plays chess"
authors = ["Clemens Horn <me@clemenshorn.com>"]
readme = "bin/draken/README.md"
repository = "https://github.com/clemenscodes/draken/"

[dependencies]
uci = { path = "../../lib/uci" }
